### PR TITLE
i18n fixes and italian translation

### PR DESCRIPTION
**Pull request by keul**
Mainly i18n changes:

* italian translation
* i18ndude script added
* removed needs of manual translations
* removed german messages from templated and needs of "en" translation folder

Other changes:

* re-enabled the "view" tab (not sure why it was disabled)
* Now use DataGridField 1.9+, with new features like required column value, column description. I was also planning to require 1.9.1+ where DateColumn has been added but there's no real change in the UI right now (PR https://github.com/collective/Products.DataGridField/pull/15 is not merged)

### CODE REVIEW

**Comment by jone** [comment]
Hey, thanks for your work!

It looks good, I'll update the German translations after merging.

Just a note on the ``runi18ndude.sh`` script:
We usually have ``development.cfg`` creating a [`bin/i18n-build`](https://github.com/4teamwork/ftw.recipe.translations#id2) script.
The ``development.cfg`` was missing, I've added it to ``master``.
So I'll remove your script after merging so that we can follow our company policy :wink:

I also discovered that the ``required`` in the DataGridField is not very handy in combination with ``auto_insert=True``: an empty line is always automatically inserted, leading to a validation error:
bildschirmfoto 2015-05-06 um 09 51 49
I'll remove the ``auto_insert`` flag.

**Comment by jone** [comment]
I've released ``ftw.poodle = 1.5.0`` with your changes.

**Comment by keul** [comment]
@jone thanks!
About the issue with DataGridField required + autoinsert, I will open an issue there, maybe I will try to fix it in future.

**Comment by jone** [comment]
ok thanks!
auto-insert is disabled in `ftw.poodle = 1.5.0`

**Pull request merged**
